### PR TITLE
esx_burgershot EN translation

### PR DESCRIPTION
**Pull request by Mascotte45IE**
Translated the entire script from Spanish to English. I'll later add better support for multiple languages. Future updates will include use of mythic notify & progress bar. 

Job delivery missions will also be made at some point

### CODE REVIEW

**Comment by KingMacking** [comment]
Nice work ! Thanks for updating it, poll merged :)

**Comment by Mascotte45IE** [comment]
I'll add better functionality to the language translation next. Even when I wrote an English locale file I still had to edit a lot of things in client and server to get everything translated - so next update will be in regards to translation so the script can be more available to more people

**Comment by Mascotte45IE** [comment]
I might have a fix for the billing shortly available. You have someone you could test it with or are you able to help me test it when its done?

**Comment by KingMacking** [comment]
Yeah, the billing works fine i think, and yes, i can test it, if you want you can add me on discord to have a better conversation :)
King Macking#8770

**Comment by Mascotte45IE** [comment]
Ah ok, I saw the comment --not working you had in the server.lua file and assumed it wasn't so I put in the latest template esx_billing uses

**Comment by KingMacking** [comment]
Yeah, thats an old comment xd

**Comment by KingMacking** [comment]
So, yo have discord to talk ? it's better tan this

**Comment by Mascotte45IE** [comment]
Yep, I sent you a friend request

**Pull request merged**
